version: '3'
services:
  watch_over: 
    image: watch-over
    command: sh -c "node index.js"
    restart: always
    volumes:
      - ./config.json:/app/config.json
      - ./list.json:/app/list.json