version: '3'
services:
  watch_over: 
    image: watch-over
    command: node index.js
    restart: always
    environment:
      - TZ=Europe/Paris
    volumes:
      - ./config.json:/app/config.json
      - ./list.json:/app/list.json